version: "3"

services:
  server:
    build: server/
    command: python ./server.py
    ports:
      - "9100:1234"
    volumes:
      - ./server:/server
    restart: unless-stopped

  client:
    build: client/
    command: python ./client.py
    depends_on:
      - server
    restart: unless-stopped
